### ISSUE TITLE
Implement get_collectedby for PandoraCollection and PandoraSubject

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/aiu#11]
I did not see a `get_collectedby` (or equivalent) for `PandoraCollection` or `PandoraSubject`. Such a function would need to descend into TEPs and acquire the organization names that created these collections. This way a resulting story would have access to this metadata for visualization.

**Comment by himarshaj** [comment]
Issue fixed
https://github.com/oduwsdl/aiu/pull/13
