### ISSUE TITLE
URIs returned from some PandoraCollection and PandoraSubject methods have an extra slash

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/aiu#12]
There is an extra slash before the identifier in some URIs returned from the code.

For subjects:
```
In [1]: ps = PandoraSubject(83)

In [2]: ps.subject_uri
Out[2]: 'http://pandora.nla.gov.au/subject//83'
```

For collections:
```
In [1]: pc = PandoraCollection(12022)

In [2]: pc.collection_uri
Out[2]: 'http://pandora.nla.gov.au/col//12022'

```

Some web clients and web servers will not redirect these correctly and calling code should not have to create a workaround.

**Comment by himarshaj** [comment]
Issue fixed
https://github.com/oduwsdl/aiu/pull/13
